baseURL: "https://leloykun.github.io" 
title: Franz Louis Cesista
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv.pdf
          weight: 1
        - name: Papers
          url: papers/
          weight: 2
        - name: Personal Projects
          url: personal-projects/
          weight: 3
        # - name: Courses
        #   url: courses/
        #   weight: 2
        # - name: Data
        #   url: data/
        #   weight: 3 
        - name: Ponder (Blog)
          url: ponder/
          weight: 4

params:
    description: "Mathematician | Machine Learning (AI) Research Scientist"
    author: Franz Louis Cesista
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2, 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    images:
        - cover.png
    profileMode:
        enabled: true
        title: <span style="color:#011F5B">Franz Louis Cesista</span>
        subtitle:
            Building things 👨‍🍳🚀 • Soon <span style="color:#011F5B">**Research Engineer**</span> at [will announce soon] • prev **Machine Learning (AI) Research Scientist, Full-Stack Software Engineer, & Data Engineer** at [Expedock Software Inc.](https://expedock.com) • <span style="color:#011F5B">**2x IOI & 2x ICPC World Finalist**</span> • Mathematics at the [Ateneo de Manila University](https://www.ateneo.edu/)<br><br>

            Geometric Deep Learning • Multimodal Machine Learning • Information Retrieval • Structured Generation
        imageUrl: "picture.png"
        imageWidth: 160
        imageHeight: 160
        imageTitle: Franz Louis Cesista
        buttons:
            - name: CV
              url: cv.pdf
            - name: Papers
              url: papers/
            - name: Personal Projects
              url: personal-projects/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
            - name: Ponder (Blog)
              url: ponder/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
    socialIcons:
        - name: Email
          url: mailto:franzlouiscesista@gmail.com
        - name: GitHub
          url: https://github.com/leloykun
        - name: LinkedIn
          url: https://www.linkedin.com/in/franzcesista/
        - name: Twitter
          url: https://twitter.com/leloykun
        - name: Substack
          url: https://ponder.substack.com
    social:
        twitter: leloykun
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
        text: "Franz Louis Cesista"
        icon: favicon.ico
        iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
